### ISSUE TITLE
Story submission should use POST body instead of GET query parameter

### ISSUE THREAD

**Issue by Apelsin** [TylerWasniowski/WritersUnblocked#17]
I meant to submit this on Monday...

**Comment by Jonathan-Weinstein** [comment]
I think I fixed this in what I am about to commit, see the CSRF note too `in storys index.html.eex`. Perhaps just going to the index should be POST instead of GET, because it modifies the lock state?

**Comment by TylerWasniowski** [comment]
Resolved by Jon with: [dc3ce1f513ea9f5ebbe1ad4106cf6268f761c716](https://github.com/TylerWasniowski/WritersUnblocked/commit/dc3ce1f513ea9f5ebbe1ad4106cf6268f761c716)
