### ISSUE TITLE
How to handle finished stories? Also linkable view story by id.

### ISSUE THREAD

**Issue by Jonathan-Weinstein** [TylerWasniowski/WritersUnblocked#18]
Ideas:
* A separate table, so in-progress-stories, and finished-stories.
* Add flag column to (the only?) story table.

Also, need some kind of a way to see completed stories. The simplest is to view a specific one by id,
which can also be cool if it can be linked like people do with imgur on things like reddit comments.
Could look like: http://writers-unblocked/view/3345

**Comment by Apelsin** [comment]
A finished flag column makes sense to me

**Comment by TylerWasniowski** [comment]
I agree, I think the best option is a finished column. It is simple and effective.

**Comment by Apelsin** [comment]
merged in #19
